import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { JsonApiClient } from "@drupal-api-client/json-api-client";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps() {
  const client = new JsonApiClient(
    "https://dev-drupal-api-client-poc.pantheonsite.io"
  );
  const articles = await client.getCollection("node--article");
  return { props: { articles } };
}

export default function Home({ articles }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          {articles.data.map((article) => (
            <a
              href={article.attributes.path.alias}
              className={styles.card}
              key={article.id}
            >
              <h2>{article.attributes.title}</h2>
              <p>
                Read more <span>-&gt;</span>
              </p>
            </a>
          ))}
        </div>
      </main>
    </>
  );
}
